Updated crawl script

diff --git a/nutch/bin/crawl b/nutch/bin/crawl
--- a/nutch/bin/crawl
+++ b/nutch/bin/crawl
@@ -97,6 +97,11 @@ CRAWL_PATH="$2"
 LIMIT="$3"
 OUTPUTDIR="$4"
 
+# Check if output directory already exist
+if [ -d "$OUTPUTDIR" ]; then
+  echo "Error: Output directory already exist!!!"
+  exit 1
+fi
 
 # convert wait time to seconds for compatibility reasons
 if [ "$WAIT" != "-1" ]; then
@@ -117,7 +122,8 @@ numTasks=`expr $numSlaves \* 2`
 
 # number of urls to fetch in one iteration
 # 250K per task?
-sizeFetchlist=`expr $numSlaves \* 50000`
+#sizeFetchlist=`expr $numSlaves \* 50000`
+sizeFetchlist=16000
 
 # time limit for feching
 timeLimitFetch=180
@@ -138,7 +144,8 @@ fi
 
 # note that some of the options listed here could be set in the
 # corresponding hadoop site xml param file
-commonOptions="-D mapreduce.job.reduces=$numTasks -D mapred.child.java.opts=-Xmx1000m -D mapreduce.reduce.speculative=false -D mapreduce.map.speculative=false -D mapreduce.map.output.compress=true"
+#commonOptions="-D mapreduce.job.reduces=$numTasks -D mapred.child.java.opts=-Xmx1000m -D mapreduce.reduce.speculative=false -D mapreduce.map.speculative=false -D mapreduce.map.output.compress=true"
+commonOptions="-D mapreduce.job.reduces=16 -D mapreduce.job.maps=8 -D mapred.child.java.opts=-Xmx8192m -D mapreduce.map.memory.mb=8192 -D mapreduce.reduce.speculative=false -D mapreduce.map.speculative=false -D mapreduce.map.output.compress=true"
 
  # check that hadoop can be found on the path
 if [ $mode = "distributed" ]; then
@@ -161,11 +168,28 @@ function __bin_nutch {
         echo "Error running:"
         echo "  $bin/nutch $@"
         echo "Failed with exit value $RETCODE."
-         echo "Error running $@, please check me!" | mail -s "Crawl Error" $RECIPIENTS
+        echo "Error running $bin/nutch $@, please check me!" | mail -s "Crawl Error" $RECIPIENTS
         exit $RETCODE
     fi
 }
 
+
+function __bin_dumper {
+    # run $bin/dumper, exit if exit value indicates error
+
+    echo "$bin/dumper $@" ;# echo command and arguments
+    "$bin/dumper" "$@"
+
+    RETCODE=$?
+    if [ $RETCODE -ne 0 ]
+    then
+        echo "Error running:"
+        echo "  $bin/dumper $@"
+        echo "Failed with exit value $RETCODE."
+        echo "Error running $bin/dumper $@, please check me!" | mail -s "Crawl Error" $RECIPIENTS
+        exit $RETCODE
+    fi
+}
 
 
 # initial injection
@@ -263,7 +287,8 @@ do
   fi
 
   echo "Dumping out using commoncrawl"
-  __bin_nutch commoncrawldump -segment "$CRAWL_PATH"/segments/$SEGMENT -outputDir "$OUTPUTDIR"/$SEGMENT &
+  __bin_dumper $bin/nutch $CRAWL_PATH $OUTPUTDIR $SEGMENT &
+  #__bin_nutch commoncrawldump -segment "$CRAWL_PATH"/segments/$SEGMENT -outputDir "$OUTPUTDIR"/$SEGMENT &
 
   #######################################################
   # The following commands fall into WebGraph territory
@@ -285,5 +310,5 @@ do
   #__bin_nutch nodedumper $commonOptions -scores -topn 1000 -webgraphdb "$CRAWL_PATH" -output "$CRAWL_PATH"/dump/scores
 
 done
-echo "Crawl complete, please check me!" | mail -s "Crawl complete" $RECIPIENTS
+echo "Crawl complete for Seed: ${SEEDDIR}, please check me!" | mail -s "Crawl complete: ${SEEDDIR}" $RECIPIENTS
 exit 0
